object ProgressView: TProgressView
  Left = 0
  Top = 0
  Margins.Left = 5
  Margins.Top = 5
  Margins.Right = 5
  Margins.Bottom = 5
  BorderIcons = []
  BorderStyle = bsToolWindow
  ClientHeight = 173
  ClientWidth = 533
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -17
  Font.Name = 'Tahoma'
  Font.Style = []
  FormStyle = fsStayOnTop
  Position = poOwnerFormCenter
  OnResize = FormResize
  PixelsPerInch = 144
  TextHeight = 21
  object StatusLabel: TLabel
    AlignWithMargins = True
    Left = 3
    Top = 3
    Width = 527
    Height = 89
    Margins.Bottom = 0
    Align = alClient
    Alignment = taCenter
    AutoSize = False
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -20
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentFont = False
    WordWrap = True
  end
  object BottomPanel: TPanel
    Left = 0
    Top = 126
    Width = 533
    Height = 47
    Margins.Left = 5
    Margins.Top = 5
    Margins.Right = 5
    Margins.Bottom = 5
    Align = alBottom
    BevelOuter = bvNone
    TabOrder = 0
    object CancelButton: TButton
      AlignWithMargins = True
      Left = 5
      Top = 5
      Width = 112
      Height = 37
      Margins.Left = 5
      Margins.Top = 5
      Margins.Right = 5
      Margins.Bottom = 5
      Align = alLeft
      Cancel = True
      Caption = 'Cancel'
      DoubleBuffered = True
      ModalResult = 2
      ParentDoubleBuffered = False
      TabOrder = 0
      OnClick = CancelButtonClick
    end
  end
  object ProgressBar: TProgressBar
    AlignWithMargins = True
    Left = 3
    Top = 98
    Width = 527
    Height = 25
    Margins.Top = 6
    Align = alBottom
    TabOrder = 1
  end
end
