object ProgressView: TProgressView
  Left = 0
  Top = 0
  BorderIcons = []
  BorderStyle = bsToolWindow
  ClientHeight = 115
  ClientWidth = 349
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  FormStyle = fsStayOnTop
  Position = poScreenCenter
  OnResize = FormResize
  TextHeight = 13
  object StatusLabel: TLabel
    AlignWithMargins = True
    Left = 2
    Top = 2
    Width = 345
    Height = 59
    Margins.Left = 2
    Margins.Top = 2
    Margins.Right = 2
    Margins.Bottom = 0
    Align = alClient
    Alignment = taCenter
    AutoSize = False
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentFont = False
    WordWrap = True
    ExplicitLeft = 8
    ExplicitTop = 8
    ExplicitWidth = 317
    ExplicitHeight = 50
  end
  object BottomPanel: TPanel
    Left = 0
    Top = 84
    Width = 349
    Height = 31
    Align = alBottom
    BevelOuter = bvNone
    TabOrder = 0
    ExplicitTop = 72
    ExplicitWidth = 341
    object CancelButton: TButton
      AlignWithMargins = True
      Left = 3
      Top = 3
      Width = 75
      Height = 25
      Align = alLeft
      Cancel = True
      Caption = 'Cancel'
      DoubleBuffered = True
      ModalResult = 2
      ParentDoubleBuffered = False
      TabOrder = 0
      OnClick = CancelButtonClick
    end
  end
  object ProgressBar: TProgressBar
    AlignWithMargins = True
    Left = 2
    Top = 65
    Width = 345
    Height = 17
    Margins.Left = 2
    Margins.Top = 4
    Margins.Right = 2
    Margins.Bottom = 2
    Align = alBottom
    TabOrder = 1
    ExplicitTop = 53
    ExplicitWidth = 337
  end
end
