object IPAddressView: TIPAddressView
  Left = 0
  Top = 0
  Width = 192
  Height = 22
  TabOrder = 0
  object ColonLabel: TLabel
    AlignWithMargins = True
    Left = 133
    Top = 0
    Width = 3
    Height = 22
    Margins.Left = 4
    Margins.Top = 0
    Margins.Right = 0
    Margins.Bottom = 0
    Align = alLeft
    Caption = ':'
    ExplicitHeight = 15
  end
  object IPEditPanel: TPanel
    AlignWithMargins = True
    Left = 4
    Top = 0
    Width = 125
    Height = 22
    Margins.Left = 4
    Margins.Top = 0
    Margins.Right = 0
    Margins.Bottom = 0
    Align = alLeft
    BevelOuter = bvNone
    TabOrder = 0
    object Byte2PeriodLabel: TLabel
      Left = 87
      Top = 0
      Width = 3
      Height = 22
      Align = alLeft
      Caption = '.'
      ExplicitHeight = 15
    end
    object Byte1PeriodLabel: TLabel
      Left = 56
      Top = 0
      Width = 3
      Height = 22
      Align = alLeft
      Caption = '.'
      ExplicitHeight = 15
    end
    object Byte3PeriodLabel: TLabel
      Left = 118
      Top = 0
      Width = 3
      Height = 22
      Align = alLeft
      Caption = '.'
      ExplicitHeight = 15
    end
    object IPByte2Edit: TEdit
      AlignWithMargins = True
      Left = 28
      Top = 0
      Width = 28
      Height = 22
      Margins.Left = 0
      Margins.Top = 0
      Margins.Right = 0
      Margins.Bottom = 0
      Align = alLeft
      Alignment = taCenter
      BorderStyle = bsNone
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -12
      Font.Name = 'Segoe UI'
      Font.Style = []
      MaxLength = 3
      ParentFont = False
      TabOrder = 1
      Text = '168'
      OnKeyPress = IPByteEditKeyPress
      OnKeyUp = IPByteEditKeyUp
    end
    object IPByte1Edit: TEdit
      AlignWithMargins = True
      Left = 0
      Top = 0
      Width = 28
      Height = 22
      Margins.Left = 0
      Margins.Top = 0
      Margins.Right = 0
      Margins.Bottom = 0
      Align = alLeft
      Alignment = taCenter
      BorderStyle = bsNone
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -12
      Font.Name = 'Segoe UI'
      Font.Style = []
      MaxLength = 3
      ParentFont = False
      TabOrder = 0
      Text = '192'
      OnChange = IPByteEditChange
      OnKeyPress = IPByteEditKeyPress
      OnKeyUp = IPByteEditKeyUp
    end
    object IPByte3Edit: TEdit
      AlignWithMargins = True
      Left = 59
      Top = 0
      Width = 28
      Height = 22
      Margins.Left = 0
      Margins.Top = 0
      Margins.Right = 0
      Margins.Bottom = 0
      Align = alLeft
      Alignment = taCenter
      BorderStyle = bsNone
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -12
      Font.Name = 'Segoe UI'
      Font.Style = []
      MaxLength = 3
      ParentFont = False
      TabOrder = 2
      Text = '1'
      OnKeyPress = IPByteEditKeyPress
      OnKeyUp = IPByteEditKeyUp
    end
    object IPByte4Edit: TEdit
      AlignWithMargins = True
      Left = 90
      Top = 0
      Width = 28
      Height = 22
      Margins.Left = 0
      Margins.Top = 0
      Margins.Right = 0
      Margins.Bottom = 0
      Align = alLeft
      Alignment = taCenter
      BorderStyle = bsNone
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -12
      Font.Name = 'Segoe UI'
      Font.Style = []
      MaxLength = 3
      ParentFont = False
      TabOrder = 3
      Text = '229'
      OnKeyPress = IPByteEditKeyPress
      OnKeyUp = IPByteEditKeyUp
    end
  end
  object IPPortEdit: TEdit
    AlignWithMargins = True
    Left = 140
    Top = 0
    Width = 36
    Height = 22
    Margins.Left = 4
    Margins.Top = 0
    Margins.Right = 0
    Margins.Bottom = 0
    Align = alLeft
    BorderStyle = bsNone
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -12
    Font.Name = 'Segoe UI'
    Font.Style = []
    MaxLength = 5
    NumbersOnly = True
    ParentFont = False
    TabOrder = 1
    Text = '5555'
  end
end
