object IPAddressView: TIPAddressView
  Left = 0
  Top = 0
  Width = 336
  Height = 39
  Margins.Left = 5
  Margins.Top = 5
  Margins.Right = 5
  Margins.Bottom = 5
  TabOrder = 0
  PixelsPerInch = 168
  object ColonLabel: TLabel
    AlignWithMargins = True
    Left = 233
    Top = 0
    Width = 5
    Height = 39
    Margins.Left = 7
    Margins.Top = 0
    Margins.Right = 0
    Margins.Bottom = 0
    Align = alLeft
    Caption = ':'
    ExplicitHeight = 30
  end
  object IPEditPanel: TPanel
    AlignWithMargins = True
    Left = 7
    Top = 0
    Width = 219
    Height = 39
    Margins.Left = 7
    Margins.Top = 0
    Margins.Right = 0
    Margins.Bottom = 0
    Align = alLeft
    BevelOuter = bvNone
    TabOrder = 0
    object Byte2PeriodLabel: TLabel
      Left = 103
      Top = 0
      Width = 5
      Height = 39
      Margins.Left = 9
      Margins.Top = 9
      Margins.Right = 9
      Margins.Bottom = 9
      Align = alLeft
      Caption = '.'
      ExplicitLeft = 99
    end
    object Byte1PeriodLabel: TLabel
      Left = 49
      Top = 0
      Width = 5
      Height = 39
      Margins.Left = 9
      Margins.Top = 9
      Margins.Right = 9
      Margins.Bottom = 9
      Align = alLeft
      Caption = '.'
      ExplicitLeft = 45
    end
    object Byte3PeriodLabel: TLabel
      Left = 157
      Top = 0
      Width = 5
      Height = 39
      Margins.Left = 9
      Margins.Top = 9
      Margins.Right = 9
      Margins.Bottom = 9
      Align = alLeft
      Caption = '.'
      ExplicitLeft = 145
    end
    object IPByte2Edit: TEdit
      AlignWithMargins = True
      Left = 54
      Top = 0
      Width = 49
      Height = 39
      Margins.Left = 0
      Margins.Top = 0
      Margins.Right = 0
      Margins.Bottom = 0
      Align = alLeft
      Alignment = taCenter
      BorderStyle = bsNone
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -21
      Font.Name = 'Segoe UI'
      Font.Style = []
      MaxLength = 3
      ParentFont = False
      TabOrder = 1
      Text = '168'
      OnKeyPress = IPByteEditKeyPress
      OnKeyUp = IPByteEditKeyUp
      ExplicitLeft = 49
    end
    object IPByte1Edit: TEdit
      AlignWithMargins = True
      Left = 0
      Top = 0
      Width = 49
      Height = 39
      Margins.Left = 0
      Margins.Top = 0
      Margins.Right = 0
      Margins.Bottom = 0
      Align = alLeft
      Alignment = taCenter
      BorderStyle = bsNone
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -21
      Font.Name = 'Segoe UI'
      Font.Style = []
      MaxLength = 3
      ParentFont = False
      TabOrder = 0
      Text = '192'
      OnChange = IPByteEditChange
      OnKeyPress = IPByteEditKeyPress
      OnKeyUp = IPByteEditKeyUp
    end
    object IPByte3Edit: TEdit
      AlignWithMargins = True
      Left = 108
      Top = 0
      Width = 49
      Height = 39
      Margins.Left = 0
      Margins.Top = 0
      Margins.Right = 0
      Margins.Bottom = 0
      Align = alLeft
      Alignment = taCenter
      BorderStyle = bsNone
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -21
      Font.Name = 'Segoe UI'
      Font.Style = []
      MaxLength = 3
      ParentFont = False
      TabOrder = 2
      Text = '1'
      OnKeyPress = IPByteEditKeyPress
      OnKeyUp = IPByteEditKeyUp
      ExplicitLeft = 103
    end
    object IPByte4Edit: TEdit
      AlignWithMargins = True
      Left = 162
      Top = 0
      Width = 49
      Height = 39
      Margins.Left = 0
      Margins.Top = 0
      Margins.Right = 0
      Margins.Bottom = 0
      Align = alLeft
      Alignment = taCenter
      BorderStyle = bsNone
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -21
      Font.Name = 'Segoe UI'
      Font.Style = []
      MaxLength = 3
      ParentFont = False
      TabOrder = 3
      Text = '229'
      OnKeyPress = IPByteEditKeyPress
      OnKeyUp = IPByteEditKeyUp
      ExplicitLeft = 157
    end
  end
  object IPPortEdit: TEdit
    AlignWithMargins = True
    Left = 245
    Top = 0
    Width = 63
    Height = 39
    Margins.Left = 7
    Margins.Top = 0
    Margins.Right = 0
    Margins.Bottom = 0
    Align = alLeft
    BorderStyle = bsNone
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -21
    Font.Name = 'Segoe UI'
    Font.Style = []
    MaxLength = 5
    NumbersOnly = True
    ParentFont = False
    TabOrder = 1
    Text = '5555'
  end
end
