object OptionsView: TOptionsView
  Left = 0
  Top = 0
  Margins.Left = 6
  Margins.Top = 6
  Margins.Right = 6
  Margins.Bottom = 6
  Caption = 'Codex Options'
  ClientHeight = 1208
  ClientWidth = 1624
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -22
  Font.Name = 'Tahoma'
  Font.Style = []
  Position = poOwnerFormCenter
  PixelsPerInch = 192
  TextHeight = 27
  object SectionSplitter: TSplitter
    Left = 424
    Top = 0
    Width = 8
    Height = 1140
    Margins.Left = 6
    Margins.Top = 6
    Margins.Right = 6
    Margins.Bottom = 6
    MinSize = 60
  end
  object CommandButtonsPanel: TPanel
    Left = 0
    Top = 1140
    Width = 1624
    Height = 68
    Margins.Left = 6
    Margins.Top = 6
    Margins.Right = 6
    Margins.Bottom = 6
    Align = alBottom
    BevelOuter = bvNone
    TabOrder = 0
    object CancelButton: TButton
      AlignWithMargins = True
      Left = 1468
      Top = 6
      Width = 150
      Height = 56
      Margins.Left = 6
      Margins.Top = 6
      Margins.Right = 6
      Margins.Bottom = 6
      Align = alRight
      Cancel = True
      Caption = 'Cancel'
      DoubleBuffered = True
      ModalResult = 2
      ParentDoubleBuffered = False
      TabOrder = 0
    end
    object OKButton: TButton
      AlignWithMargins = True
      Left = 1306
      Top = 6
      Width = 150
      Height = 56
      Margins.Left = 6
      Margins.Top = 6
      Margins.Right = 6
      Margins.Bottom = 6
      Align = alRight
      Caption = 'OK'
      Default = True
      DoubleBuffered = True
      ParentDoubleBuffered = False
      TabOrder = 1
      OnClick = OKButtonClick
    end
  end
  object SectionsTreeView: TTreeView
    AlignWithMargins = True
    Left = 6
    Top = 6
    Width = 412
    Height = 1128
    Margins.Left = 6
    Margins.Top = 6
    Margins.Right = 6
    Margins.Bottom = 6
    Align = alLeft
    HideSelection = False
    Indent = 38
    MultiSelectStyle = []
    ReadOnly = True
    RowSelect = True
    ShowButtons = False
    ShowLines = False
    TabOrder = 1
    OnChange = SectionsTreeViewChange
  end
  object SectionPanel: TPanel
    AlignWithMargins = True
    Left = 438
    Top = 6
    Width = 1180
    Height = 1128
    Margins.Left = 6
    Margins.Top = 6
    Margins.Right = 6
    Margins.Bottom = 6
    Align = alClient
    BevelOuter = bvNone
    TabOrder = 2
  end
end
