object ADBConnectView: TADBConnectView
  Left = 0
  Top = 0
  Margins.Left = 5
  Margins.Top = 5
  Margins.Right = 5
  Margins.Bottom = 5
  Caption = 'ADB Connect'
  ClientHeight = 456
  ClientWidth = 918
  Color = clBtnFace
  Constraints.MinWidth = 628
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -17
  Font.Name = 'Tahoma'
  Font.Style = []
  Position = poOwnerFormCenter
  OnClose = FormClose
  PixelsPerInch = 144
  TextHeight = 21
  object IPAddressLabel: TLabel
    AlignWithMargins = True
    Left = 5
    Top = 69
    Width = 908
    Height = 21
    Margins.Left = 5
    Margins.Top = 5
    Margins.Right = 5
    Margins.Bottom = 5
    Align = alTop
    Caption = 'Target Device IP Address && Port:'
    ExplicitWidth = 246
  end
  object ReminderLabel: TLabel
    AlignWithMargins = True
    Left = 5
    Top = 5
    Width = 908
    Height = 54
    Margins.Left = 5
    Margins.Top = 5
    Margins.Right = 5
    Margins.Bottom = 5
    Align = alTop
    AutoSize = False
    Caption = 
      'Remember that the target device needs to first be connected to a' +
      ' PC or Mac and this command run on it: adb tcpip 5555'#13#10'This only' +
      ' has to be done once since the device was last restarted'
    WordWrap = True
    ExplicitWidth = 909
  end
  object ButtonsPanel: TPanel
    Left = 0
    Top = 408
    Width = 918
    Height = 48
    Margins.Left = 5
    Margins.Top = 5
    Margins.Right = 5
    Margins.Bottom = 5
    Align = alBottom
    BevelOuter = bvNone
    TabOrder = 2
    object CloseButton: TButton
      AlignWithMargins = True
      Left = 800
      Top = 5
      Width = 112
      Height = 38
      Margins.Left = 5
      Margins.Top = 5
      Margins.Right = 6
      Margins.Bottom = 5
      Align = alRight
      Caption = 'Close'
      DoubleBuffered = True
      ParentDoubleBuffered = False
      TabOrder = 2
      OnClick = CloseButtonClick
    end
    object ConnectButton: TButton
      AlignWithMargins = True
      Left = 677
      Top = 5
      Width = 112
      Height = 38
      Margins.Left = 5
      Margins.Top = 5
      Margins.Right = 6
      Margins.Bottom = 5
      Align = alRight
      Caption = 'Connect'
      Default = True
      DoubleBuffered = True
      ParentDoubleBuffered = False
      TabOrder = 1
      OnClick = ConnectButtonClick
    end
    object DismissCheckBox: TCheckBox
      AlignWithMargins = True
      Left = 12
      Top = 0
      Width = 660
      Height = 48
      Margins.Left = 12
      Margins.Top = 0
      Margins.Right = 0
      Margins.Bottom = 0
      Align = alClient
      Caption = 'Dismiss on successful connect'
      Checked = True
      State = cbChecked
      TabOrder = 0
    end
  end
  object IPPanel: TPanel
    AlignWithMargins = True
    Left = 0
    Top = 95
    Width = 918
    Height = 36
    Margins.Left = 0
    Margins.Top = 0
    Margins.Right = 0
    Margins.Bottom = 0
    Align = alTop
    BevelOuter = bvNone
    TabOrder = 0
    object RecentIPLabel: TLabel
      AlignWithMargins = True
      Left = 524
      Top = 0
      Width = 58
      Height = 33
      Margins.Left = 0
      Margins.Top = 0
      Margins.Right = 12
      Align = alRight
      Alignment = taRightJustify
      Caption = 'Recent:'
      Layout = tlCenter
      ExplicitLeft = 515
      ExplicitHeight = 21
    end
    object IPComboBox: TComboBox
      AlignWithMargins = True
      Left = 594
      Top = 0
      Width = 324
      Height = 29
      Margins.Left = 0
      Margins.Top = 0
      Margins.Right = 0
      Margins.Bottom = 0
      Align = alRight
      Style = csDropDownList
      TabOrder = 0
      OnChange = IPComboBoxChange
    end
    object IPAddressPanel: TPanel
      AlignWithMargins = True
      Left = 0
      Top = 0
      Width = 524
      Height = 36
      Margins.Left = 0
      Margins.Top = 0
      Margins.Right = 0
      Margins.Bottom = 0
      Align = alClient
      BevelOuter = bvNone
      Padding.Left = 3
      Padding.Top = 3
      Padding.Right = 3
      Padding.Bottom = 3
      TabOrder = 1
    end
  end
  object OutputMemo: TMemo
    AlignWithMargins = True
    Left = 5
    Top = 136
    Width = 908
    Height = 267
    Margins.Left = 5
    Margins.Top = 5
    Margins.Right = 5
    Margins.Bottom = 5
    Align = alClient
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -20
    Font.Name = 'Consolas'
    Font.Style = []
    ParentFont = False
    ScrollBars = ssVertical
    TabOrder = 1
  end
end
